name: End-to-end tests
on: 
 pull_request:
  branches: [ main ]
jobs:
  Executing_UI_E2E_Tests :
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup npm package
       run: npm init -y && npm install
     - name: Running e2e Tests
       run: npm run e2e:chrome
