name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v2
       with:
        persist-credentials: false

     - name: Reconfigure git to use HTTP authentication
       run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/
     - name: Setup npm package
       run: npm init -y && npm install

     - name: Checkout
       uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
     - name: Cypress run
       uses: cypress-io/github-action@v4
